pattern: ^(master|develop){1}$|^(feat|fix|release)\/.+$
errorMsg: |
  Branch naming convention error.
  Your branch doesn't follow the naming conventions, please follow these steps to rename it accrodingly:
  (where <remote> is the name of your remote, usually origin, check it with: git remote show)
  1. git branch -m <old_name> <new_name>
  2. git push <remote> --delete <old_name>
  3. git branch --unset-upstream <new_name>
  4. git push <remote> <new_name>
  5. git push <remote> --set-upstream <new_name>
